# This is Nginx Proxy Manager
#
# These should be the defualt credentials
# Email: admin@example.com
# Password: changeme
#
version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:81'
      - '443:443'
    volumes:
      - /home/docker/data:/data
      - /home/docker/letsencrypt:/etc/letsencrypt

networks:
   nginxproxy:
     driver: bridge
     ipam:
       driver: default
       config:
         - subnet: 172.16.0.0/16