  # This is Nginx Proxy Manager
  #
  # These should be the defualt credentials
  # Email: admin@example.com
  # Password:   
  #
  version: '3.1'
  services:
    app:
      image: 'jc21/nginx-proxy-manager:latest'
      restart: unless-stopped
      networks:
        - proxy
      ports:
        - '81:81'
        - '80:80'
        - '443:443'
      volumes:
        - /home/docker/nginxproxymanager/data:/data
        - /home/docker/nginxproxymanager/letsencrypt:/etc/letsencrypt

  networks:
    proxy:
      external: true
