# This is for portainer-ce
#
# You should get Prompt to make a new login
#
version: '3.8'
services:
  portainer-ce:
    ports:
      - '9000:9000'
      - '8000:8000'
    container_name: portainer
    networks:
      - nginxproxy
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/home/docker/portainer:/data'
    image: 'portainer/portainer-ce:latest'

networks:
  nginxproxy:
    external: true